apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: irinaplay-pw-tls
spec:
  secretName: irinaplay-pw
  issuerRef:
    name: letsencrypt-prod        
    kind: ClusterIssuer
  commonName: irinaplay.pw
  dnsNames:
    - irinaplay.pw
    - www.irinaplay.pw
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - irinaplay.pw
          - www.irinaplay.pw